[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cbc-nlp"
version = "0"
dependencies = ["numpy", "spacy", "nltk", "gensim", "tika", "boto3", "beautifulsoup4", "lxml", "s3-streaming"]

[project.optional-dependencies]
dev = ["pytest", "pip-tools"]